apiVersion: v1
kind: Pod
metadata:
  name: notary
  labels:
    app: notary
spec:
  imagePullSecrets:
  - name: regsecret 
  containers:
  - name: notary
    image: {{ image }}
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /data
        name: pv
      - mountPath: /truststore
        name: truststore
        readOnly: true
    env:
      - name: "NAMESPACE"
        value: "{{ namespace }}"
    ports:
      - containerPort: 1300
  volumes:
    - name: pv
      persistentVolumeClaim:
        claimName: notary
    - name: truststore
      secret:
        secretName: truststore-3.0.0
