language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6-dev-i386 mingw-w64 gcc-mingw-w64-x86-64 g++-mingw-w64-i686 binutils-mingw-w64-x86-64 lib32z1-dev zlib1g-dev g++-mingw-w64-x86-64

env:
  matrix:
  - BUILD_STEP="jdk-test"
  - BUILD_STEP="test"
  - BUILD_STEP="mode=debug test"
  - BUILD_STEP="process=interpret test"
  - BUILD_STEP="mode=debug bootimage=true test"
  - BUILD_STEP="bootimage=true test"
  - BUILD_STEP="openjdk=$JAVA_HOME test"
  - BUILD_STEP="tails=true continuations=true heapdump=true test"
  - BUILD_STEP="codegen-targets=all test"
  - BUILD_STEP="PUBLISH"
  global:
  - TERM=dumb
  - secure: rh1utD4shKmYtokItuRYEF9WsfTnvZO5XqnTU4DHTS7quHHgLihtOO2/3+B+2W2hEd5Obr2or8zx+zmzWcNUyLokZ0j/FRLWSScNkLzTtm12pupLrncY+/g1NIdfbhn+OLRIzBz6zB6m6a2qWFEJ+bScUNGD/7wZVtzkujqlDEE=
  - secure: j9DOzZMCYk/BzhKK9u4XMKpCzyGOsvP2cLTp6cXE7/tkWDAPVv6BFmeqNbiLTEqk0aGX+HYbY/2YVtpRZmDzfeWtnBFF5mL1Y1tgzx1Kf155C+P6rZgt5PiQTUdXlp2umuRifY1BbXAPc3DZ2UOPUjWKnLHVbZLQRgO1zimmMx8=

matrix:
  fast_finish: true

script: ./test/ci.sh STEP ${BUILD_STEP}
