apiVersion: batch/v1
kind: Job
metadata:
  name: partya-init
spec:
  template:
    spec:
      imagePullSecrets:
        - name: "registrysecret"
      initContainers:
      - name: partya-initial-registration
        image: haregistry.azurecr.io/r3-corda:3.2
        args: ["--initial-registration", "--network-root-truststore", "certificates/network-root-truststore.jks", "--network-root-truststore-password", "password"]
        volumeMounts:
        - name: partya-configmap-volume
          mountPath: /opt/corda/node.conf
          subPath: node.conf
        - name: partya-empty-dir-certificates
          mountPath: /opt/corda/certificates
        - name: network-root-truststore-secret-volume
          mountPath: /opt/corda/certificates/network-root-truststore.jks
          subPath: network-root-truststore.jks

      - name: partya-just-generate-node-info
        image: haregistry.azurecr.io/r3-corda:3.2
        args: ["--just-generate-node-info"]
        volumeMounts:
        - name: partya-configmap-volume
          mountPath: /opt/corda/node.conf
          subPath: node.conf
        - name: partya-empty-dir-certificates
          mountPath: /opt/corda/certificates

      containers:
      - name: upload-partya-certificates-secret
        image: haregistry.azurecr.io/kubectl
        args: ["kubectl create secret generic partya-certificates-secret --from-file=/opt/corda/certificates"]
        volumeMounts:
        - name: partya-empty-dir-certificates
          mountPath: /opt/corda/certificates
      
      volumes:
      - name: partya-configmap-volume
        configMap:
          name: partya-configmap
      - name: partya-empty-dir-certificates
        emptyDir: {}
      - name: network-root-truststore-secret-volume
        secret:
          secretName: network-root-truststore-secret
      - name: partya-empty-dir-node-info
        emptyDir: {}

      restartPolicy: Never

  backoffLimit: 0