apiVersion: batch/v1
kind: Job
metadata:
  name: doorman-generate-network-parameters
spec:
  template:
    spec:
      imagePullSecrets:
        - name: "registrysecret"
      containers:
      - name: doorman-generate-network-parameters
        image: {{ image }}
        args: ["--config-file", "doorman-init.conf", "--set-network-parameters", "network-parameters.conf"]
        volumeMounts:
        - name: doorman-configmap-volume
          mountPath: /opt/doorman/doorman-init.conf
          subPath: doorman-init.conf
        - name: doorman-certificates-secret-volume
          mountPath: /opt/doorman/certificates
        - name: doorman-configmap-volume
          mountPath: /opt/doorman/network-parameters.conf
          subPath: network-parameters.conf
        - name: notary-node-info-secret-volume
          mountPath: /opt/doorman/notaryNodeInfo
          subPath: notaryNodeInfo

      volumes:
      - name: doorman-configmap-volume
        configMap:
          name: doorman-configmap
      - name: doorman-certificates-secret-volume
        secret:
          secretName: doorman-certificates-secret
      - name: notary-node-info-secret-volume
        secret:
          secretName: notary-node-info-secret

      restartPolicy: Never

  backoffLimit: 0