apiVersion: v1
kind: Pod
metadata:
  name: {{ name }}-cold
  labels:
    app: {{ name }}
spec:
  imagePullSecrets:
    - name: "registrysecret"
  containers:
    - name: {{ name }}-cold
      image: {{ image }}
      volumeMounts:
        - name: {{ name }}-configmap-volume
          mountPath: /opt/corda/node.conf
          subPath: node.conf
        - name: {{ name }}-certificates-secret-volume
          mountPath: /opt/corda/certificates
        - name: {{ name }}-artemis-file-pvc-volume
          mountPath: /opt/corda/artemis

  volumes:
  - name: {{ name }}-configmap-volume
    configMap:
      name: {{ name }}-configmap
  - name: {{ name }}-certificates-secret-volume
    secret:
      secretName: {{ name }}-certificates-secret
  - name: {{ name }}-artemis-file-pvc-volume
    persistentVolumeClaim:
      claimName: {{ name }}-artemis-file-pvc

  restartPolicy: Never