apiVersion: v1
kind: Pod
metadata:
  name: {{ name }}
  labels:
      app: {{ name }}
spec:
  imagePullSecrets:
    - name: "registrysecret"
  containers:
  - name: {{ name }}
    image: {{ image }}
    volumeMounts:
    - name: {{ name }}-configmap-volume
      mountPath: /opt/corda-firewall/firewall.conf
      subPath: firewall.conf
    - name: network-parameters-secret-volume
      mountPath: /opt/corda-firewall/network-parameters
      subPath: network-parameters
{% for bridge_node in bridge_nodes %}    - name: {{ bridge_node }}-certificates-secret-volume
      mountPath: /opt/corda-firewall/certificates{% endfor %}

  volumes:
  - name: {{ name }}-configmap-volume
    configMap:
      name: {{ name }}-configmap
  - name: network-parameters-secret-volume
    secret:
      secretName: network-parameters-secret
  {% for bridge_node in bridge_nodes %}- name: {{ bridge_node }}-certificates-secret-volume
    secret:
      secretName: {{ bridge_node }}-certificates-secret{% endfor %}

  restartPolicy: Never