apiVersion: v1
kind: Service
metadata:
  name: hanode
spec:
  ports:
    - name: p2p
      port: 10002
      protocol: TCP
      targetPort: 10002
    - name: rpc
      port: 10003
      protocol: TCP
      targetPort: 10003
  selector:
    app: hanode
