apiVersion: v1
kind: Pod
metadata:
  name: bridge
  labels:
      app: bridge
spec:
  imagePullSecrets:
    - name: "registrysecret"
  containers:
  - name: bridge
    image: haregistry.azurecr.io/corda-firewall
    volumeMounts:
    - name: bridge-configmap-volume
      mountPath: /opt/corda-firewall/firewall.conf
      subPath: firewall.conf
    - name: network-parameters-secret-volume
      mountPath: /opt/corda-firewall/network-parameters
      subPath: network-parameters
    - name: partya-certificates-secret-volume
      mountPath: /opt/corda-firewall/certificates

  volumes:
  - name: bridge-configmap-volume
    configMap:
      name: bridge-configmap
  - name: network-parameters-secret-volume
    secret:
      secretName: network-parameters-secret
  - name: partya-certificates-secret-volume
    secret:
      secretName: partya-certificates-secret

  restartPolicy: Never